spring:
  application:
    name: j
  boot:
    admin:
      client:
        url: "http://localhost:8081"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: logs/application.log
  level:
    root: INFO